all:
	inkscape --export-filename="bump.png" -D bump.svg
	inkscape --export-filename="crack.png" -D crack.svg
	inkscape --export-filename="hole.png" -D hole.svg
	inkscape --export-filename="patch.png" -D patch.svg


clean:
	rm -f *.png