get:
	wget https://unpkg.com/leaflet@1.9.3/dist/leaflet.css -O leaflet.css
	wget https://unpkg.com/leaflet@1.9.3/dist/leaflet.js -O leaflet.js
	wget https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css -O bootstrap.min.css